### ISSUE TITLE
Open-shell case

### ISSUE THREAD

**Issue by vvp-nsk** [piecuch-group/ccq#3]
Hi!

Do you support the restricted open-shell case? If so, could you please provide a few examples? 

Thank you in advance!

With best regards, 
Victor

**Comment by kgururangan** [comment]
Certainly, CCQ adopts the spin-integrated spinorbital formulation for all CC codes, so everything is compatible with open-shell references of the ROHF type. In fact, the CC codes themselves are also fully compatible with UHF references, although we do not yet have a suitable interface for reading UHF integrals. 

Open shells are specified in the input using the multiplicity keyword. For example, if we wanted to modify the input for a CCSD calculation on F2 / cc-pVDZ taken from the tests directory to create a calculation for the F2+ doublet ion, we would do the following:

```
# System information
froz=4
nel=17
nvir=43
multiplicity=2
onebody=f2plus_vdz_2.0/onebody.inp
twobody=f2plus_vdz_2.0/twobody.inp
num_threads=1

# Calculation options
keep_bin=.false.
diis_space=6
tol=1.0e-8
max_iterations=60
calc_type=CCSD
rhf=.false.
```

The ```multiplicity``` keyword automatically partitions the electrons into alpha and beta spaces according to the occupancy resulting from the high-spin ROHF determinant. So here, the 17 electrons would be partitioned into 9 alpha and 8 beta, and after freezing the core, we have 7 alpha and 6 beta electrons being correlated in the CC calculation. Assuming the integrals specified with ```onebody.inp``` and ```twobody.inp``` come from an ROHF doublet state for F2+, this input should work.

Best,
Karthik

**Comment by vvp-nsk** [comment]
Hi!

Thanks for your detailed reply. It sounds good that open-shell case is supported. However, I am wondering on how to generate 'onebody.inp' and 'twobody.inp' files needed? Apparently, both binary files are written in a format different from 'FCIDUMP'. 

Thank you in advance!

With best regards, 
Victor Vysotskiy

**Comment by kgururangan** [comment]
So the ```onebody.inp``` and ```twobody.inp``` files require a quick explanation, and I'm sorry we didn't include this in the documentation. These are formats for writing the 1- and 2-electron integrals that are used in many research codes in our group, so it was a convenient input structure for us, however it is not a community standard, and thus it's troublesome for external users. Before I get into it, I might also point you towards our newer code called CCpy, which is under active development these days, and it contains almost all of the methods included in CCQ (and more; it includes closed- and open-shell functionalities for all methodologies except for CCSDTQ, which is only for closed-shells at the moment). It has a more natural input structure, which allows calculations to be run using FCIDUMP files or PySCF mean-field objects. Depending on what calculations you'd like to perform, it may work better for you, so if it suits your needs, I can give you more information about that.

Anyway, the ```onebody.inp``` file contains the lower triangular half (including diagonal elements) of the 1-electron integral matrix ```<p|h|q>``` in the MO basis. The ```twobody.inp``` file contains the 2-electron integrals in the chemist notation ```[pr|qs]``` (including the permutationally redundant ones) written in the form ```p  r  q  s  value```, where p, q, r, and s label spatial MO indices, starting from 1 to Norb (Norb is the total number of MOs in the problem). The final entry of the ```twobody.inp``` file contains the nuclear repulsion energy listed as ```0  0  0  0  e_nuc```.  

If you have an FCIDUMP file on hand, I can share with you a simple Python script that produces appropriate ```onebody.inp``` and ```twobody.inp``` files. In the meantime, we will update the CCQ documentation to reflect this caveat regarding the integral inputs as well as update the repository to include this helper script as well.

We apologize for this inconvenience.

Best,
Karthik

**Comment by vvp-nsk** [comment]
Dear Karthik, 

> If you have an FCIDUMP file on hand, I can share with you a simple Python script that produces appropriate `onebody.inp` and `twobody.inp` files. In the meantime, we will update the CCQ documentation to reflect this caveat regarding the integral inputs as well as update the repository to include this helper script as well.
> 

I do have FCIDUMP file and would highly appreciate it if you share with me your python script. Is it Ok if FCIDUMP was originally generated by PySCF?

With best regards, 
Victor

**Comment by kgururangan** [comment]
Yes, this should be fine. Right now, it might be best for me to share this script with you via e-mail. Please provide me with your e-mail (you can also contact me at gururang@msu.edu).

Best,
Karthik
